name: pull-request
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Copy repository
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: yarn install --frozen-lockfile
      
      - name: Lint code
        run: yarn run lint

      - name: 'Create env file'
        run: |
          touch .env
          echo MONGO_TEST_CONNECTION_URI=${{ secrets.MONGO_TEST_CONNECTION_URI }} >> .env
          echo MONGO_CONNECTION_URI=${{ secrets.MONGO_CONNECTION_URI }} >> .env
          echo MONGODB_URL=${{ secrets.MONGODB_URL }} >> .env
          cat .env
      
      - name: Run tests
        run: yarn run test
